services:
  driver_1:
    build:
      context: .
      dockerfile: Dockerfile.driver
    container_name: manual_driver_1
    environment:
      KAFKA_BROKER: 172.21.42.11:9092  # <-- HOST PC IP
    command: python driver/ev_driver.py DRIVER-001 172.21.42.11 5000
    #                                               ^^^^^^^^^^^^
    #                                               HOST PC IP
    network_mode: host
    stdin_open: true
    tty: true