# ============================================================================
# docker-compose-windows.yml
# Windows HOST machine - Runs CENTRAL + Kafka infrastructure
# ============================================================================

services:
  # ==========================================================================
  # Infrastructure - Zookeeper & Kafka
  # ==========================================================================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: evcharging_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - evcharging_net

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: evcharging_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # IMPORTANT: Replace with your Windows machine's actual IP
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.100:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"
    networks:
      - evcharging_net

  # ==========================================================================
  # CENTRAL - Control Center (Interactive)
  # ==========================================================================
  central:
    build:
      context: .
      dockerfile: Dockerfile.central
    container_name: evcharging_central
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    networks:
      - evcharging_net
    stdin_open: true
    tty: true

networks:
  evcharging_net:
    driver: bridge

volumes:
  zookeeper_data:
  kafka_data: