services:
  driver_1:
    build:
      context: .
      dockerfile: Dockerfile.driver
    container_name: manual_driver_1
    environment:
      KAFKA_BROKER: 172.21.42.11:9092  # <-- HOST PC IP
    command: python driver/ev_driver.py DRIVER-001 172.21.42.11 5000
    #                                               ^^^^^^^^^^^^
    #                                               HOST PC IP
    network_mode: host
    stdin_open: true
    tty: true

  driver_2:
    build:
      context: .
      dockerfile: Dockerfile.driver
    container_name: manual_driver_2
    environment:
      KAFKA_BROKER: 172.21.42.11:9092  # <-- HOST PC IP
    command: python driver/ev_driver.py DRIVER-002 172.21.42.11 5000
    #                                               ^^^^^^^^^^^^
    #                                               HOST PC IP
    network_mode: host
    stdin_open: true
    tty: true

  driver_auto:
    build:
      context: .
      dockerfile: Dockerfile.driver
    container_name: auto_driver
    environment:
      KAFKA_BROKER: 172.21.42.11:9092  # <-- HOST PC IP
    command: sh -c 'sleep 5 && python driver/ev_driver_auto.py DRIVER-AUTO 172.21.42.11 5000 data/charging_requests.txt'
    #                                                                       ^^^^^^^^^^^^
    #                                                                       HOST PC IP
    volumes:
      - ./data:/app/data
    network_mode: host