# ============================================================================
# docker-compose-debian.yml
# Debian CLIENT machine - Runs Charging Points + Drivers
# ============================================================================

services:
  # ==========================================================================
  # Charging Point 1 - Engine + Monitor
  # ==========================================================================
  cp_engine_1:
    build:
      context: .
      dockerfile: Dockerfile.cp
    container_name: evcharging_cp_engine_1
    environment:
      # IMPORTANT: Replace 192.168.1.100 with your Windows machine's IP
      KAFKA_BROKER: 192.168.1.100:9092
    # Connect to CENTRAL on Windows host
    command: python charging_point/ev_cp_engine.py CP-001 40.5 -3.1 0.30 192.168.1.100 5000
    ports:
      - "6001:6001"
    network_mode: host
    stdin_open: true
    tty: true

  cp_monitor_1:
    build:
      context: .
      dockerfile: Dockerfile.cp
    container_name: evcharging_cp_monitor_1
    depends_on:
      - cp_engine_1
    environment:
      KAFKA_BROKER: 192.168.1.100:9092
    # Connect to local engine and Windows CENTRAL
    command: python charging_point/ev_cp_monitor.py CP-001 localhost 6001 192.168.1.100 5000
    network_mode: host
    stdin_open: true
    tty: true

  # ==========================================================================
  # Charging Point 2 - Engine + Monitor
  # ==========================================================================
  cp_engine_2:
    build:
      context: .
      dockerfile: Dockerfile.cp
    container_name: evcharging_cp_engine_2
    environment:
      KAFKA_BROKER: 192.168.1.100:9092
    command: python charging_point/ev_cp_engine.py CP-002 40.4 -3.2 0.35 192.168.1.100 5000
    ports:
      - "6002:6002"
    network_mode: host
    stdin_open: true
    tty: true

  cp_monitor_2:
    build:
      context: .
      dockerfile: Dockerfile.cp
    container_name: evcharging_cp_monitor_2
    depends_on:
      - cp_engine_2
    environment:
      KAFKA_BROKER: 192.168.1.100:9092
    command: python charging_point/ev_cp_monitor.py CP-002 localhost 6002 192.168.1.100 5000
    network_mode: host
    stdin_open: true
    tty: true

  # ==========================================================================
  # Driver 1 - Interactive Manual Mode
  # ==========================================================================
  driver_1:
    build:
      context: .
      dockerfile: Dockerfile.driver
    container_name: evcharging_driver_1
    environment:
      KAFKA_BROKER: 192.168.1.100:9092
    command: >
      sh -c 'sleep 5 && python driver/ev_driver.py DRIVER-001 192.168.1.100 5000'
    network_mode: host
    stdin_open: true
    tty: true

  # ==========================================================================
  # Driver 2 - Interactive Manual Mode
  # ==========================================================================
  driver_2:
    build:
      context: .
      dockerfile: Dockerfile.driver
    container_name: evcharging_driver_2
    environment:
      KAFKA_BROKER: 192.168.1.100:9092
    command: >
      sh -c 'sleep 6 && python driver/ev_driver.py DRIVER-002 192.168.1.100 5000'
    network_mode: host
    stdin_open: true
    tty: true

  # ==========================================================================
  # Auto Driver - File-based automation (optional)
  # ==========================================================================
  driver_auto:
    build:
      context: .
      dockerfile: Dockerfile.driver
    container_name: evcharging_driver_auto
    environment:
      KAFKA_BROKER: 192.168.1.100:9092
    command: >
      sh -c 'sleep 5 && python driver/ev_driver_auto.py DRIVER-AUTO 192.168.1.100 5000 data/charging_requests.txt'
    volumes:
      - ./data:/app/data
    network_mode: host